![alt text](https://lh3.googleusercontent.com/jS2nj0Ju7rvJJangnpFrnveoLlMAVc-Ee-k38WW3bRT1rpOooDKa8c3Uh2hZs5j6-XNc1ZFry07GtQTX8sYRpyZGgz8TZuBpGw75pAZqSKQRSfKA0Isy3I-222AHDlZa1WNAvFGmQLfeR4S96qK3agRN-br82Od1243W4uVZbFmbkZPykYy4_qDeE2UrbT1nVr8QZccLXjjtjiJRM8WQ_8eZFSRUBP1BMQg5AG6l7tdGXuWlQDmqFOFcDcEQE5ZX30N7TIcDSOiMWjp0gGZgtMfaR983h4NP8dUp-ej-Vo1D4FSpa_zTpjvKRrpbfnVir1LpIw0yC9OjD7aCMtLcul9Npe-voMkiJgz5XNvFatCgq5WmfcoaDDvkkEQZgp7LQoOqqprzvdItdiyWagMtCVQONtypoZhc2kQQkfav2M0sC9kG4AXDJ6nOlpi8iSbJSVVPKHN9wzGzN1gxo2dDtaua9VfHd5MTOWiRV6ArL6pzwzSzAPSAgUFZZhc4RHGzk5ChHsJBaO3gzvn8GF4Cr7P7GahgXEhw98u1Z0VlNqDmp37B4cUHm5dujBm7jQXGTvPqM5zuDHwiviFId6OMjcjW6xZNckM9_KM8opmUYN_RKP-YPs51qrz9NVksS73JOhHpBHtVQMDCFycT6ZSKv-zdwZN7_FW7=w2160-h856-no)

# 들어가며

## Google Colab 사용 방법

- 방향키 ↑↓: 셀 간 이동
- Enter: 편집모드
- Ctrl + Enter: 셀 실행
- Shift + Enter: 셀 실행 + 다음 셀 선택

---

- Ctrl +M D: 셀 삭제
- Ctrl + M K: 셀 위로 이동
- Ctrl + M J: 셀 아래로 이동

#**1. NumPy의 존재 이유**


![alt text](https://lh3.googleusercontent.com/AP7oMf3hAk2jjhu_cHRNZ6JHxjOZ9FOtthMkSw_wPoRBgSuroW8s4BhP5vAeOrMoBlc7fTeX79ItwpWn5Wmek4wunewkSVe_emEmmFxJUlFbM-a4mFE06ghc5dmpsa9pIRbXQbadTpnOYw9lY9Ujr-UKp5rqi_-IUEh7SFUoWhcGv2ch60Kz3u1j0TWukwW4xCOXd85gkesdMHsaMo_qllLu1mzWeIrABxeASD3n8RuWyiETGJruH5mpiq0X7PkprxJkbwTmaOfwQTolZp64xW05yvXb2xEN_dJuHaWvhCdX05RVcqjw6JjWrqnmLKSwYKgHUy-l4yXBgsZFSh0Vi-di4-DB4e5LxNJa_9ykJuC9sr_msdeub6EMBJnvwziHIkdqwmfUUEl13EHFpkbt2AsJVeSj-ctJTUIxGCx1kD2OPA0VID_BTNpJDBXH1RtMC8JoRysIClD4NVL0tSh96R0ZownNqE8FZlextg86VQuhP7_CRSFtuEdzD5I0SxHDqPWhHzA9Okb5gmDwBykEf55jla53ta1thdxwKG8uJAm9ksW0lnsmG7HcA0l6UJibRJVhnf4-jEmJ_0CvCQ61rf0lbP_-bJOGOy3HZP5NrqOfVbJvX0Ey9UYURK1H7XuhDdydyTi4JY_V-7htYv7RxKUTED5Bd7R1WiQnCIYwbrDPbTyR6KHZgO7ydMp37hOlr9Fw745ASonaxuyPA2XTdRSCXg=w708-h371-no)

NumPy는 Pandas, Scikit-learn, Tensorflow등 데이터 사이언스 분야에서 사용되는 라이브러리들의 토대가 되는 라이브러리입니다. NumPy 그 자체로는 높은 수준의 데이터 분석 기능을 제공하지 않지만 NumPy를 활용해 데이터를 Python상에서 표현하고 다룰 줄 알아야만 데이터 분석이라는 그 이후 단계로 나아갈 수 있습니다.

이번 강의에서는 데이터 분석의 토대가 될 NumPy의 기본 기능들과 더 빠르고 효율적인 연산을 위한 NumPy 활용법들을 다룰 예정입니다.

## 데이터 과학에서 다차원 배열의 필요성

### 숫자 자료형

파이썬에서는 데이터를 숫자형 변수에 저장할 수 있습니다.

세명의 학생들로 이루어진 반이 있고 이 학생들의 수학점수를 각각의 **숫자형 변수**에 저장하는 경우 아래처럼 처리할 수 있습니다.

In [ ]:
MathScore1 = 11
MathScore2 = 12
MathScore3 = 13

점수들의 합과, 평균은 아래처럼 구할 수 있습니다.

In [ ]:
MathScoreSum = MathScore1 + MathScore2 + MathScore3
MathScoreAverage = MathScoreSum/3

print("수학점수 합: {}".format(MathScoreSum))
print("수학점수 평균: {}".format(MathScoreAverage))

수학점수 합: 36
수학점수 평균: 12.0


만약 새로운 학생이 전학을 와서 시험을 쳤고 이 학생의 성적을 추가한 점수들의 합과 평균을 구하려면 어떻게 해야 할까요?

새로운 변수를 추가해야 합니다.

In [ ]:
MathScore4 = 14

그리고 합과 평균을 구하는 코드 역시 수정해야합니다.

In [ ]:
MathScoreSum = MathScore1 + MathScore2 + MathScore3 + MathScore4  # 추가된 MathScore4를 합 구할때 고려
MathScoreAverage = MathScoreSum/4                                 # 수정: 분모를 3에서 4로 수정

print("수학점수 합: {}".format(MathScoreSum))
print("수학점수 평균: {}".format(MathScoreAverage))

수학점수 합: 50
수학점수 평균: 12.5


### 리스트 자료형

추가된 데이터를 새로 선언해 주는것은 어쩔수 없다 하더라도 합과 평균을 구하는 코드를 매번 변경하는건 비효율적인 일입니다.

리스트 자료형에 데이터를 저장하면 이 문제를 해결할 수 있습니다.

다섯명의 학생들로 이루어진 반이 있고 이 학생들의 수학점수를 **리스트**에 저장하는 경우 아래처럼 처리할 수 있습니다.

In [ ]:
MathScoreList = [11, 12, 13]

print(MathScoreList)

[11, 12, 13]


점수들의 합과, 평균은 아래처럼 구할 수 있습니다.

In [ ]:
listMathScoreSum = 0      # 변수 선언&초기화
listMathScoreAverage = 0  # 변수 선언&초기화

for e in MathScoreList:
  listMathScoreSum += e   # listMathScoreSum = listMathScoreSum + e 와 동일한 코드

listMathScoreAverage = listMathScoreSum / len(MathScoreList)

print("수학점수 합: {}".format(listMathScoreSum))
print("수학점수 평균: {}".format(listMathScoreAverage))

수학점수 합: 36
수학점수 평균: 12.0


만약 새로운 학생이 전학을 와서 시험을 쳤고 이 학생의 성적을 추가한 점수들의 합과 평균을 구하려면 어떻게 해야 할까요?

~~새로운 변수를 추가해야 합니다.~~

기존의 리스트에 새로운 데이터를 추가하면 됩니다.

In [ ]:
# append: list의 끝에 요소를 추가할 때 사용하는 메서드
MathScoreList.append(14)  # 데이터 추가

~~그리고 합과 평균을 구하는 코드 역시 수정해야합니다.~~

새로운 데이터가 추가되더라도 평균과 합을 구하는 **코드는 수정 없이 그대로 사용할 수 있습니다**.

In [ ]:
listMathScoreSum = 0      # 변수 선언&초기화
listMathScoreAverage = 0  # 변수 선언&초기화

for e in MathScoreList:
  listMathScoreSum += e   # listMathScoreSum = listMathScoreSum + e 와 동일한 코드

listMathScoreAverage = listMathScoreSum / len(MathScoreList)

print("수학점수 합: {}".format(listMathScoreSum))
print("수학점수 평균: {}".format(listMathScoreAverage))

수학점수 합: 50
수학점수 평균: 12.5


만약 시험문제의 오류가 발견되어 모두 정답처리를 해 모든 학생의 점수를 1점씩 올려줘야 하는 상황에서는 어떻게 해야할까요?

반복문이나 List comprehension같은 방법이 있습니다.

**반복문**

In [ ]:
MathScoreList2 = []
for e in MathScoreList:
  MathScoreList2.append(e+1)


print(MathScoreList2)

[12, 13, 14, 15]


**List Comprehension**

In [ ]:
MathScoreList3 = [e +1 for e in MathScoreList]

print(MathScoreList3)

[12, 13, 14, 15]


## 파이썬 기본 자료형으로 구현한 다차원 배열

#### Nested List (중첩 리스트)

1반의 점수가 11, 12, 13

2반의 점수가 21, 22, 23

3반의 점수가 31, 32, 33점이라고 한다면,

리스트 안에 리스트를 넣어 위 데이터를 아래처럼 나타낼 수 있습니다.

In [ ]:
MathScoreNestedList = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

print(MathScoreNestedList)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


<p class="aligncenter">
    <img src="https://lh3.googleusercontent.com/pQw2wvQVpsV40t7Uk6O-iNMwVX0GUesvvA-snrEVl1lGWeRsrDjU-2YlkO0jlW7XFMmQNVQchD1XM4sbWVSPtTWjvSc50mY2iuFKNYc72N-rSvymejq4dCpuG4WeheZ2M4tqkJzO37xcujHDe4MJNc0URISUgTXt2452rMh2wDrCVKOa0Ywh85x3cqL9IRYJxjUm0yKmjtCTJhDSXZVEXvnc1RtQoLJzviQsSp6yDdHrA7UwZNBzgMQc3_ol7PUREYY3tLXTXs0_eA-XaJ_J0ONIk2xUnW4B_erXbjeA-UDXFg76BXSmq0CHmcmIewz__z7QI8W7XMS-p087h2mvgxHQFC9tOE2SKQl8oLHFKPm5QrViTs1vrH6sHSYfVoEnJ4XHtV4GPEU0gRco2aYF6x7lfM6I_FGDG0Xm1lncuZUxJ6ger9CF5KB0t881bJbnAvx3WdpPNPw23uG2CqqcadZ5phhvLhh7UDT_kmvq9p04w2E1OTRGxnpljA0qppfFIAAB9wcKdD7cJW48cYjoFTnxKxRaIJYATgquEQ7uzLXsmMu_JeWQpe7gjPlc0lTzguOYp5Rn0vLRxeYZhsN2rwO-g_9XBgZ5_smxUuVYLQeujJvJL41NwOkLtWHWe-r1B449P7Y2Y1uktbd0v5xDRPsde4MynOh3TJWUVw8S2bTP82giPHRryz3l3NRfMaxAJ-fgEggmJV7RNelOAnKYIXnNLA=w1124-h422-no" alt="centered image"  width="400" height="200">
</p>

> (source: https://cognitiveclass.ai/blog/nested-lists-multidimensional-numpy-arrays/)

각 원소에 1을 더하는 코드는 아래와 같습니다.

In [ ]:
MathScoreNestedList2 = []

for list in MathScoreNestedList:
  tempList = []

  for e in list:
    tempList.append(e+1)

  MathScoreNestedList2.append(tempList)


print(MathScoreNestedList2)

[[12, 13, 14], [22, 23, 24], [32, 33, 34]]


#### 문제점

1차원에서 2차원으로 데이터의 차원이 증가하니 반복문도 하나 더 사용해야 합니다.

데이터의 차원이 증가할수록 코드는 복잡해질 수밖에 없습니다.

## NumPy로 구현한 다차원 배열

**NumPy**를 사용하면 다차원배열을 효율적으로 다룰 수 있습니다.

`import numpy as np` 형태로 import하는게 일반적입니다.

In [ ]:
import numpy as np

mathScoreNdarray = np.array(MathScoreNestedList)
# mathScoreNdarray = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

print(mathScoreNdarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mathScoreNdarray

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

각 원소에 1을 더하려면

In [ ]:
mathScoreNdarray + 1 # 이것이 바로 브로드캐스팅! 후반부에 다룰 예정입니다.

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

NumPy에 구현된 메서드를 활용해 합이나 평균도 쉽게 구할 수 있습니다.

In [ ]:
# 전체 합 구하기
np.sum(mathScoreNdarray)

198

In [ ]:
# 전체 평균 구하기
np.mean(mathScoreNdarray)

22.0

In [ ]:
# 열의 평균 구하기
np.mean(mathScoreNdarray, axis=0)

array([21., 22., 23.])

In [ ]:
# 행의 평균 구하기
np.mean(mathScoreNdarray, axis=1)

array([12., 22., 32.])

In [ ]:
# 산술평균
np.mean(range(1,11))

In [ ]:
# 가중평균
np.average(range(1,11), weights=range(10,0,-1))   #10~0까지 -1씩 가중치를 줌 (1에서 가중치가 가장 큼)

## 파이썬 기본 자료형과 넘파이 비교

### Helper class

#### 정의



In [ ]:
# 이해하지 않아도 됩니다. NumPy 강의와 무관하며 시간을 측정하기 위한 클래스 입니다.
import time
class Timer(object):
    def __init__(self, name=None):
        self.name = name

    def __enter__(self):
        self.tstart = time.time()

    def __exit__(self, type, value, traceback):
        if self.name:
            print('[%s]' % self.name)
        print('Elapsed: %s' % (time.time() - self.tstart))


#### 사용법

In [ ]:
with Timer('여기에 이름을 입력하세요'):
   # 아래에 시간측정을 하고자 하는 코드를 입력하세요.
  time.sleep(1)

[여기에 이름을 입력하세요]
Elapsed: 1.00130295753479


### 비교

In [ ]:
# 크기가 100개 이내인 경우 NumPy는 순수 파이썬 구현 보다도 오히려 낮은 성능을 보이는 경향이 있습니다.

# rows ,cols가 2일떄 아래 타이머코드를 실행해 보고 rows, cols를 1000으로 바꾼 뒤 다시 코드를 실행 해 보세요.
# 차이를 볼 수 있습니다.
rows = 500  # 행 # axis = 1
cols = 500  # 열 # axis = 0
sampleRand2Darray = np.random.rand(rows, cols)  # ndarry 선언
sampleRand2Dlist = sampleRand2Darray.tolist()   # nested list 선언

In [ ]:
# rows, cols가 1000넘어갈땐 실행 하지 마세요. (노트북 멈춥니다.)
sampleRand2Darray  # numpy array

array([[0.33523019, 0.04861149],
       [0.06234464, 0.57221328]])

In [ ]:
# rows, cols가 1000넘어갈땐 실행 하지 마세요. (노트북 멈춥니다.)
sampleRand2Dlist  # nested list (파이썬 리스트의 중첩)

[[0.3352301882741151, 0.048611491478404156],
 [0.0623446369216164, 0.5722132802892029]]

In [ ]:
with Timer('파이썬 기본 자료형 사용 - 모든 원소의 합 구하기'):
  sum = 0

  for list in sampleRand2Dlist:
    for e in list:
      sum += e

with Timer('파이썬 기본 자료형 사용 - 모든 원소에 1 더하기'):
  sampleRand2Dlist2 = []

  for list in sampleRand2Dlist:
    tempList = []

    for e in list:
      tempList.append(e+1)

    sampleRand2Dlist2.append(tempList)

print("----------------------------------------------")

with Timer('NumPy사용 - 모든 원소의 합 구하기'):
  sum = np.sum(sampleRand2Darray)

with Timer('NumPy사용 - 모든 원소에 1 더하기'):
  sampleRand2Darray2 = sampleRand2Darray + 1

[파이썬 기본 자료형 사용 - 모든 원소의 합 구하기]
Elapsed: 0.03088665008544922
[파이썬 기본 자료형 사용 - 모든 원소에 1 더하기]
Elapsed: 0.0394139289855957
----------------------------------------------
[NumPy사용 - 모든 원소의 합 구하기]
Elapsed: 0.0010216236114501953
[NumPy사용 - 모든 원소에 1 더하기]
Elapsed: 0.0018672943115234375


#### NumPy 장점

- 코어 부분이 C로 구현되어 동일한 연산을 하더라도 Python에 비해 속도가 빠름
- C언어는 컴퓨터 어셈블 언어와 일대일 대응, Python은 인터프리터 거쳐서 상대적으로 느림
- 라이브러리에 구현되어있는 함수들을 활용해 짧고 간결한 코드 작성 가능
- (효율적인 메모리 사용이 가능하도록 구현됨)

### (참고) ndarray가 list보다 빠른 이유

![alt text](https://lh3.googleusercontent.com/JD1ljKEm4S_4hvIu8XqTLUw75AjB6K-ElhXY6oMqBiPVEPIkNpHjlMLKsTbpWMIXOZ1X3Ompb-v3lI5FHqlyWWOFR0Pg3vLsio9_8OSgFoAywjGAC6oY85kCahlx-rJtSqW9M3szyXBVjrnlUYIo3opwX7ch7BYaV6sLReXAOwcJThS4f-E-PQWOzwSsCerL_-QEi_wcEV_4Aef_q0u9lrcjvZX-OwW-AcSILKPIB3yoZar4zTTOPHz-miQ4yq2gOktHY1wR4izuJ5SmIT2feKEdP6sD5So8I24vdt1mKKjro3fQenb9ExtH-zAxlJQarxaDnklts7801rG56sa6sE69ZJBp3ZzJ8qr59SM1xf2t9dU1WHcIvMWM5g39B85aIYHRCFmqfwaAx6Gl8x7To_33nyLpc8hA6gIbPQ46O6N_I3-s2G_t5E1dt9mEr0v9fgnco5ib53RP7myVnH6prsSOP4n0hzSvf_gBvKsYIJ2TJA-631XcIR5K7VgE6kycjbVGtTlfDn5fTbVbjgJyIR2xhjPFQ85rxpLnPD0NLE8LzGzjA7bo3CJiBjd0CUHbjbUbUINtLHm8H8lT9U7vZIEzLSIA4dvO3SujTC8R8F7dPBO5Bc91VTWF1mqUftGeWmIdJ61E-KlKb6lRYnRdNq55scpLa3sX2Y2v3tCFq4uHvUM2VO4gkyi_9WNZciyoq1gQD8e9_Ig3aUsWdU87JJMQNw=w638-h479-no)

> (source: https://image.slidesharecdn.com/numpy20160519-160516164831/95/numpy-8-638.jpg)

**파이썬 list가 느린 이유**

- 파이썬 리스트는 결국 포인터의 배열 (리스트의 주소가 저장되어 있어 주소에 할당된 데이터가 산재되어 있음)
- 경우에 따라서 각각 객체가 메모리 여기저기 흩어져 있음
- 그러므로 캐시 활용이 어려움
- (구조상 느린 이유) : 데이터는 다른 곳에 있고, 데이터의 주소값을 받음
- (언어상 느린 이유) : python언어 - 인터프리터방식을 거치기 때문



**NumPy ndarray가 빠른 이유**

- ndarray는 타입을 명시하여 원소의 배열로 데이터를 유지 (주소가 저장되어 있지 않고 원소의 값, 데이터가 적혀있음, 연속된 데이터 값)
- 다차원 데이터도 연속된 메모리 공간이 할당됨
- 많은 연산이 dimensions과 strides를 잘 활용하면 효율적으로 가능
  - 가령 transpose는 strides를 바꾸는 것으로 거의 공짜
- ndarray 구현 방식을 떠올리면 어떻게 성능을 낼 수 있는지 상상 가능
- (구조상 빠른 이유) : 데이터를 그대로 받음
- (언어상 빠른 이유) : 코어 부분이 C언어로 구현됨


- 예) NumPy에서 Transpose 구현

- Transpose : 대각선을 기준으로 데이터가 바뀜 (2,3의 위치가 바뀜)
- x.Strides : (2,1)
데이터를 읽을 때 1 읽고 다음 행에 들어갈 데이터는 2칸 건너뛴 3을 / 다음 열에 들어갈 데이터는 1칸 건너뛴 2를 읽어옴
- y.Strides : (1,2)
데이터를 읽을 때 1 읽고 다음 행에 들어갈 데이터는 1칸 뒤인 2를 / 다음 열에 들어갈 데이터는 2칸 건너뛴 3을 읽어옴


![alt text](https://lh3.googleusercontent.com/-cTovEUtM3SZj9_Pd12Sf_hkJpwr9hvvlOTQVC80Q697w8bsSV7I4sAru5fHmgxU7FmxZtq9ZqgvOAqZg41oFjXaEwAtLMLVmN75BIk6HClFMfC6jecLYB6sKDWQUNcLDb2Pt5Vbi8jUVb6VLyWbZGvCVYobh1ev1aNvPoCrqBtR8uv1P8E99xSoaIvzp4dvVG14b_eLBGKuTnak0P305F8OgJgQq2M0Q8_unVPygZOo-vdA9fPx8z_LpOqB0ZIqIXEhf7NmsRWk0cuuUkgJlqJselVnHnTSIVCIohQaOLAU1U_Acufab3szF4BGP-D3DUUQaPcsN-HhxIkSEaFgxuylaRbEUOdYWeXwvuYe9tzNkIzndFtWaQ0MfeBbwlEscaIRVjxsICdCdT0xvX8vpgBegnNQUSo0kT2e3JjY3VLO8YQZ28W457BMyz_2NA_hKuwcGeFWotVoN0AlUTNNQSlpwQzitwSAsi_IlVfNDRYTTTFb-9dTjD9rdgQid3khyHmelE6k1VYayHnwJsJPiD_hcNGYpUChhC5WD-05Qg-R6vrOWXCvkB0tG4Q7fxMIh1_-fhOwEyEOsH91byk4afqJx559LeHldNiDVeU6I-rJRPtkG5mrBYPr0jD2uSIDvpX0ATVesWlunIKD7kvctEidPx8I7yhbKaI96L81K5cbGg49To2OpUaNZ3ttvZiztErvTbkLhruKXIj253HWAI2Jdg=w720-h405-no)

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.int8)

y = x.T

In [ ]:
x

array([[1, 2],
       [3, 4]], dtype=int8)

In [ ]:
y

array([[1, 3],
       [2, 4]], dtype=int8)

In [ ]:
print(x.strides)
print(y.strides)

(2, 1)
(1, 2)


# **2.다차원 배열 생성 1 (직접 입력)**

nd.array
다차원 배열
n demension array

명시적으로 값을 입력해 다차원 배열을 만드는 방법을 알아봅니다.

## 다차원 배열의 자료형

![alt text](https://lh3.googleusercontent.com/ZhC-hkgaa_zQggBdbQ8J33aW8b6Ubbccwr4dLOiVlXAuJYgBiZzRR0jcrAe9C6h26h_3xfd1UbMt6vwIpLfDffABXNKDkUT6RUZre4-j7DtYt7CFsQ1b4RdNZwfCQoSkr_BWKACQQ42krqB0Jkri4CDHGMhKgALRRiJJaQCsR0frysFtltqxiX0ScqZleBxMkADkJr8FtFKh34ERS4w3lwIqddpWd9ctgu9bJsDA19yNEmLouiwapSV7NwAXgDko3fqxo_W4CY6NU_vXxx8xoyFtaXxdXRCs2yketYJ66IP8Rv_mADUSnXfcCfgHOPlU_PzkT-cLdnfLftHgitAPrDHOqiH7EpLmgg4bO_HWIhpDwfG7iu2upN_rw-sFl64aGj4XhhbPYfmDZpnIEyrvKE4DjycH6rITqxTbhMSWfkeeUBENLusqELkVnPRikaaxYiDVPRuedOp6hNXo7R4A-TghyLn-k61kV3Ruwc14ytOWhZ0BngaDXVo-KF_ZxJUr5GuaFOZbi4UKhXbvnObRZAb0QgKaCdvkYysxU31oryDHpx526hG6SW6b99CxOWbT0lBTy0RoynGz_WVV_ua_umNcmkBNMkt3u04uCUWk8a-BqMG_oVpyqNmqetASSOhCZNbisBzkEgmo4sDbdqsNlFcY3fa-Og8mB1UNmC2uWl5RefSArRAoKn6KxZpcr6qJdl8YWT98ncW6behEO1wLoNsdBg=w526-h413-no)

(source: https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html)

다차원 배열의 원소는 위와 같은 데이터 타입을 가질 수 있습니다.

다차원 배열의 원소는 동일한 데이터 타입을 가져야 합니다.

## 방법 1) 직접 원소를 입력해서 다차원 배열 생성하기

**np.array()**를 사용해 다차원 배열을 생성할 수 있습니다.
- np.array(list)를 넣어 numpy의 다차원 배열을 생성할 수 있다.

In [ ]:
np.array([[1,2,3], [4,5,6]]) # 2차원 배열 생성 (nested list 형식)
np.array([[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]) # 3차원 배열 생성

### bool

boolean 데이터를 입력해서 다차원 배열을 생성해봅시다.

In [ ]:
import numpy as np

boolArray = np.array([True, False, True, True, False])

In [ ]:
boolArray

array([ True, False,  True,  True, False])

In [ ]:
boolArray.dtype

dtype('bool')

### number

number 데이터를 입력해서 다차원 배열을 생성해봅시다.

정수형, 부호없는 정수형, 실수형, 복소수형이 있습니다.

#### 정수형

정수형의 default data type은 'int64'입니다.

<font color="red">(진실: default data type은 운영체제에 따라 다릅니다.)</font>

In [ ]:
intArray = np.array([[1, 2], [3, 4]])

In [ ]:
intArray

array([[1, 2],
       [3, 4]])

In [ ]:
intArray.dtype

dtype('int64')

#### 부호없는 정수형

부호없는 정수형의 default data type은 'uint64'입니다.
uint = un signed int



In [ ]:
uintArray = np.array([[1, 2], [3, 4]], dtype='uint')
uintArray = np.array([[1, 2], [3, 4]], dtype='uint64')

In [ ]:
uintArray

array([[1, 2],
       [3, 4]], dtype=uint64)

In [ ]:
uintArray.dtype

dtype('uint64')

#### 실수형

실수형의 default data type은 'float64'입니다.
- float 16으로 설정할 수 있고, 하나의 data가 차지하는 용량의 크기는 더 작지만, 표현할 수 있는 수의 범위도 더 작음

In [ ]:
floatArray = np.array([[1.1, 2.2], [3.3, 4.4]])
floatArray = np.array([[1.1, 2.2], [3.3, 4.4]], dtype='float64')

In [ ]:
floatArray

array([[1.1, 2.2],
       [3.3, 4.4]])

In [ ]:
floatArray.dtype

dtype('float64')

##### 형변환

데이터가 정수로 입력되더라도 data type을 실수형으로 명시한다면 실수형으로 자동 형변환이 일어납니다.

In [ ]:
floatArray2 = np.array([[1, 2], [3, 4]], dtype='float64')

In [ ]:
floatArray2

array([[1., 2.],
       [3., 4.]])

In [ ]:
floatArray2.dtype

dtype('float64')

##### 더 나은 방법

1.0, 2.0, 3.0, 4.0이라는 실수형 데이터를 가지는 다차원배열을 만들고 싶었다면, 아래 방법이 더 나은 코딩표준입니다.
- 정수형 데이터를 넣은 후 float64로 읽어라는 방식보단, 실수형 데이터를 넣는 아래의 방식이 더 선호됨.

In [ ]:
floatArray3 = np.array([[1., 2.], [3., 4.]])

In [ ]:
floatArray3

array([[1., 2.],
       [3., 4.]])

In [ ]:
floatArray3.dtype

dtype('float64')

##### 참고

정수형에서 실수형으로의 형변환 과정은 데이터 손실이 일어나지 않아 문제될 부분이 없지만 실수형에서 정수형으로의 형변환 과정인 반대의 경우에는 문제가 발생할 수 있습니다.

In [ ]:
intArray2 = np.array([[1.1, 2.2], [3.3, 4.4]], dtype='int')

In [ ]:
intArray2

array([[1, 2],
       [3, 4]])

실수가 정수로 형변환되며 데이터의 손실이 발생했습니다.
<font color="red">입력한 데이터와 다차원 배열내의 데이터가 다릅니다.</font>

#### (참고) 복소수형

복소수형의 default data type은 'complex128'입니다.

In [ ]:
complexArray = np.array([1+1j, 2+2j, 3+3j, 4+4j, 5+5j])

In [ ]:
complexArray

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j, 5.+5.j])

In [ ]:
complexArray.dtype

dtype('complex128')

## 방법 2) 파일에서 데이터를 입력 받아 다차원 배열 생성하기


np.genfromtxt()을 이용하여 파일에 저장된 데이터를 입력받아 다차원 배열을 생성할 수 있습니다.

하지만 사용할 일은 많지 않습니다. 그 이유는,

- NumPy ndarray는 동일한 데이터타입만을 가질 수 있습니다.
- 대부분 데이터 파일에는 하나의 데이터 타입만 있는게 아니라 정수, 실수, 문자열이 섞여 있습니다.

파일에서 데이터를 읽어올땐 NumPy의 genfromtxt()보단 **Pandas의 read_csv()나 read_excel()**을 주로 사용합니다.

### 예시

In [ ]:
# 파일 다운로드 받기
!wget -O 'mnist_train_super_small.csv' https://docs.google.com/spreadsheets/d/1lUBHgDlG5EVoZxfSF84X5jbcyynjnWSK8_weiQApt2M/export?format=csv

In [ ]:
import numpy as np
fromCSVArray = np.genfromtxt('mnist_train_super_small.csv', delimiter=',')

In [ ]:
fromCSVArray

### 구글 드라이브에서 파일 가져오기

In [ ]:
# 구글드라이브의 파일을 가져오고 싶은 경우

# 구글드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 구글드라이브내에 있는 파일 경로 지정
fromCSVArray = np.genfromtxt('/content/drive/My Drive/talk-on-seminar-numpy/resources/mnist_train_super_small.csv', delimiter=',')
# np.genfromtxt는 확장자 상관없이 binary로 읽어옴 (csv, txt 모두 가능)
# csv = comma seperated, ,로 구분된 데이터를 읽어옴

In [ ]:
fromCSVArray

# **3. 다차원 배열 생성 2 (함수)**

NumPy에 구현되어있는 함수를 활용해 다차원 배열을 만드는 방법을 알아봅니다.

https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

## numpy.empty

Return a new array of given shape and type, without initializing entries.
- 아무 값이 나옴 : 초기화 하지 않았기 때문
- (2,3) 2행 3열 데이터

In [ ]:
np.empty((4,3))

array([[5.04414716e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.empty_like(A)  # 형태를 유지한 상태로, 초기화하지 않은 상태로 random한 수를 대입

array([[102094675340523,               0,               0],
       [              0,               0,               0],
       [              0,               0,               0]])

## numpy.zeros

Return a new array of given shape and type, filled with zeros.
- 초기화를 0.0(실수)로 함

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3), dtype=int) #data type을 정수형으로 명시할 경우

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## numpy.ones

Return a new array of given shape and type, filled with ones.

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## numpy.identity

Return the identity array.
- 단위행렬
- nd.array : 다차원 배열 vs matrix : 다차원 배열이 2차원일 때

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 참고

### numpy.eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.
- np.identity는 정사각형 단위행렬만 형성 가능
- np.eye는 직사각형 단위행렬도 가능함

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3, 4, 1) # 대각선이 1칸씩 오른쪽 이동

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3, 4, -1) # 대각선이 1칸씩 왼쪽으로 이동

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### numpy.full

numpy.full(shape, fill_value, dtype=None, order='C')

Return a new array of given shape and type, filled with fill_value.
- np.full((shape parameter), 채워질 수)

In [ ]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

위 보다는 아래 방식을 선호합니다.

In [ ]:
10 * np.ones((2,3), dtype=int)

array([[10, 10, 10],
       [10, 10, 10]])

### numpy.arange

Return evenly spaced values within a given interval.

In [ ]:
# default value
# start = 0
# step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=1.0, stop=5.0, step=0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### numpy.linspace

Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

# **4.다차원 배열 다루기 1 (method로 통계값 구하기)**

통계값을 구하는 함수에 대해 알아봅니다.
- axis=0은 행을 따라 이동함
- axis=1은 열을 따라 이동함

<font color="red">이제 반복문은 사용하지 않습니다.</font>

https://docs.scipy.org/doc/numpy/reference/routines.statistics.html

![alt text](https://lh3.googleusercontent.com/zXC7mbgObMUkQoUnkfMvog5wU8Qh2bvLEwINZo7eilDpq_aun8c3D_qCvaCZhQQLnC-iz7XxFP3iWylf3RZWNsKUaw2MFU0c4Oiu3cbZIPM4AsgSSUVYlDzZKVgG-ldbaEt2vty-cqaHNqrIYNPjsN6n8gT5XbJPqEk5GJjjTfL61t5ugfaDtHjbskwoZm45x8xbWJgkilc8fZ70hWGr8tpskk_5P4G3dI9zy0-ZNTDF9R2nGknAjcmCT3cP5nKhL0YM8mhhbWxS7jTotR1A-hKBPRXbu-5tFa1W54F8k4Do17Wvhz_JNaj0EX-5z0BT8ryE6XPvsJd4vlQAAzwYKdy9oIL7KYzTiIy3vi7MicCg7opIc87ueczPBpZUv2vczrUzzOT-6Yczc9Ay2UPvzyS6SmB2QJI2gGXXvdRFZAElecn83X98psuIHAGx7xii7OplLOQLNaDN3o0tCt4v0e2mgnP8zU87MfUGMCgs-zJwCZYeJz-2rt1EHGGk0IuiiDJQ-R_X91KUE1Z76VOHOjBt_saj-UJ40dTB2w_ITArQa1dH2GhPZCz7wC4_UmwYlr1BHUiohA1ByDBHRB2cA8sBF5MU3s7F1KKWPQUcBQqf2NhQgUJTYWnvWUrgqdmvEKRVRiXwqlJiwGVc1_nCFUAOtzXqLtJAvT0mlKso-GUEPy6NPFjR-Yvv4ci_QFfhtUh87MyVYTEphY7xcNwTaswPqw=w652-h341-no)

## numpy.amin

Return the minimum of an array or minimum along an axis.

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.amin(A, 0) # 각 열에서 1행~3행 중 가장 작은 값 출력 # axis=0은 행방향으로 이동 방향
np.amin(A, axis=0)

array([1, 2, 3])

In [ ]:
np.amin(A, 1) # 각 행에서 1~3열 중 가장 작은 값 출력 # axis =1은 열방향으로 이동 방향
np.amin(A, axis=1)

array([1, 4, 7])

In [ ]:
np.amin(A) # 1~3행과 1~3열 중 가장 작은 값 출력

1

## numpy.amax

Return the maximum of an array or maximum along an axis.

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.amax(A, 0)
np.amax(A, axis=0)

array([7, 8, 9])

In [ ]:
np.amax(A, 1)
np.amax(A, axis=1)

array([3, 6, 9])

In [ ]:
np.amax(A, 1).shape

(3,)

In [ ]:
np.amax(A)

9

## numpy.ptp

Range of values (maximum - minimum) along an axis.

The name of the function comes from the acronym for ‘peak to peak’.
- 최대와 최소의 피크의 범위 -> 숫자 범위의 개형을 대략적으로 확인
- array([6, 6, 6]) 6의 크기만큼 최댓값, 최솟값이 벌어져 있음

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.ptp(A, 0)

array([6, 6, 6])

In [ ]:
np.ptp(A, 1)

array([2, 2, 2])

In [ ]:
np.ptp(A)

## numpy.median

Compute the median along the specified axis.

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.median(A, 0)

array([4., 5., 6.])

In [ ]:
np.median(A, 1)

array([2., 5., 8.])

In [ ]:
np.median(A)

5.0

## numpy.mean

Compute the arithmetic mean along the specified axis.

(가중평균을 구하려면 numpy.average를 사용해야 합니다.)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.mean(A, 0)

array([4., 5., 6.])

In [ ]:
np.mean(A, 1)

array([2., 5., 8.])

In [ ]:
np.mean(A)

5.0

## numpy.var

Compute the variance along the specified axis.

In [ ]:
np.var(A, 0)

array([6., 6., 6.])

In [ ]:
np.var(A, 1)

array([0.66666667, 0.66666667, 0.66666667])

In [ ]:
np.var(A)

6.666666666666667

## numpy.std

Compute the standard deviation along the specified axis.

In [ ]:
np.std(A, 0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
np.std(A, 1)

array([0.81649658, 0.81649658, 0.81649658])

In [ ]:
np.std(A)

2.581988897471611

# **5.다차원 배열 다루기 2 (형태 변경)**
다차원 배열에서 일부분만 가져오거나 다차원 배열의 형태를 바꾸는 방법을 알아봅니다.

https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

## 슬라이싱

파이썬 리스트와 유사하게, Numpy 배열도 슬라이싱이 가능합니다.

Numpy 배열은 다차원인 경우가 많기에, 각 차원별로 어떻게 슬라이스할건지 명확히 해야 합니다:

Numpy 배열을 슬라이싱하면, 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열입니다.

In [ ]:
import numpy as np

# shape가 (3, 4)인 2차원 배열 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

다차원배열은 아래와 같은 방법으로 슬라이싱 합니다.

`a[ : , : ]`


`a[행 슬라이싱 시작:행 슬라이싱 끝, 열 슬라이싱 시작:열 슬라이싱 끝]`


**시작값**부터 **끝값** <font color="red">전</font>까지 슬라이싱 됩니다.

In [ ]:
a[0:2, 0:4]  #0행부터 2행전까지, 0열부터 4열전까지 슬라이싱 #0행~1행 , 0열~3열 출력

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

0행부터 2행 전까지(= 1행 까지), 0열부터 4열 전까지(= 3열 까지) 슬라이스되었습니다.

**생략 가능 : 시작값이 0인 경우, 끝 값이 shape의 값과 동일한 경우**

`a[0:2, 0:4]`은 `a[:2, :]`로 표시할 수 있습니다.

In [ ]:
a[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

위 코드는 열을 슬라이싱 하지 않는 코드이며 이런 경우 열 부분은 전체 생략 가능합니다.

(행을 슬라이싱 하지 않는다고 하더라도, 행부분을 생략할 순 없습니다.)

In [ ]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**슬라이싱에 익숙해지기 전까진 생략하지말고 명시적으로 코드를 작성해주는것이 실수를 방지하는 방법입니다.**

## 인덱싱

인덱싱을 통해 원소에 접근할 수 있습니다.

두 가지 표현법이 있습니다.

In [ ]:
# 선호하는 방식
a[0, 0]

1

In [ ]:
a[0][0]

1

Numpy 배열을 슬라이싱하면, 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열입니다.

그러나 인덱싱을 한다면, 연속하지 않은 값을 가져올 수 있으니 원본과 다른 배열을 만들 수 있습니다.

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 0행, 2행만 인덱싱
a[[0, 2], ]
a[[0,2], 0:4]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
# 0열, 1열, 3열만 인덱싱
a[:, [0,1,3]]
a[0:3, [0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

## 인덱싱&슬라이싱 - 차원축소&유지

정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 차원의 배열이 생성되지만,

슬라이싱만 사용하면 원본 배열과 동일한 차원의 배열이 생성됩니다.

0번째 행을 인덱싱하는 경우와 슬라이싱 하는 경우를 비교해보겠습니다.

In [ ]:
print(a, a.shape, a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


**슬라이싱 추천** : 연산해야하는 경우 차원이 동일해야 하므로 차원이 유지되는 슬라이싱 추천!

In [ ]:
# 슬라이싱만 사용 - 차원 유지됨 - 연산해야할 경우 차원이 동일해야 함
slicedRow = a[0:1, :]
print(slicedRow, slicedRow.shape, slicedRow.ndim)

[[1 2 3 4]] (1, 4) 2


In [ ]:
# 아래와 동일한 코드
# 행:인덱싱&열:슬라이싱 혼합 사용
indexedRow = a[0] #0번행만 가져오므로 차원이 줄어듬
print(indexedRow, indexedRow.shape, indexedRow.ndim)

# 위와 동일한 코드
# 행:인덱싱&열:슬라이싱 혼합 사용
indexedRow2 = a[0, :]
print(indexedRow2, indexedRow2.shape, indexedRow2.ndim)

[1 2 3 4] (4,) 1
[1 2 3 4] (4,) 1


행이 아닌 열의 경우에도 마찬가지 입니다.

In [ ]:
# 슬라이싱만 사용
slicedCol = a[:, 0:1]
print(slicedCol, slicedCol.shape, slicedCol.ndim)

[[1]
 [5]
 [9]] (3, 1) 2


In [ ]:
# 인덱싱&슬라이싱 혼합 사용
indexedCol = a[:, 0]
print(indexedCol, indexedCol.shape, indexedCol.ndim)

[1 5 9] (3,) 1


다차원배열간 연산에서 차원이 달라 문제가 발생하는 경우가 종종 있습니다.

**특별히 인덱싱을 써야 하는 상황이 아니라면, 인덱싱보다 슬라이싱을 추천합니다.**

## 인덱싱&슬라이싱 - 값 복사&참조

인덱싱은 값을 복사해옵니다. 복사된 값을 변경해도 원본의 값은 변하지 않습니다.

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 인덱싱해서 b에 대입 -> 인덱싱할 때 값이 복사되어서 b에 대입 (원본값 유지됨)
b = a[0, 0]

# b값 수정
b = 100

print("a[0, 0]: {}".format(a[0, 0]))
print("b: {}".format(b))

a[0, 0]: 1
b: 100


슬라이싱된 배열은 원본 배열과 같은 데이터를 참조합니다.

<font color="red">즉 슬라이싱된 배열을 수정하면 원본 배열 역시 수정됩니다.</font>

In [ ]:
# a를 슬라이스하여 c 생성
c = a[1:3, 1:3]

print(c)

[[ 6  7]
 [10 11]]


In [ ]:
# c[0, 0]은 a[1, 1]과 같은 데이터입니다.
c[0, 0] = 100

print(c)
print('------------------')
print(a)

[[100   7]
 [ 10  11]]
------------------
[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


## 불리언 배열 인덱싱

불리언 배열 인덱싱을 통해 배열 속 요소를 취사선택할 수 있습니다.
- 불리언 배열 인덱싱은 **특정 조건을 만족하게 하는 요소만 선택하고자 할 때** 자주 사용됩니다.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
bool_idx = (a > 2)  # 2보다 큰 a의 요소를 찾습니다;
                    # 이 코드는 a와 shape가 같고 불리언 자료형을 요소로 하는 numpy 배열을 반환합니다,
                    # bool_idx의 각 요소는 동일한 위치에 있는 a의
                    # 요소가 2보다 큰지를 말해줍니다.

print(bool_idx)      # 출력 "[[False False]
                     #       [ True  True]
                     #       [ True  True]]"

# 불리언 배열 인덱싱을 통해 bool_idx에서
# 참 값을 가지는 요소로 구성되는
# rank 1인 배열을 구성할 수 있습니다.
print(a[bool_idx])  # 출력 "[3 4 5 6]" : bool_idx를 [bool_idx]불리언 인덱싱하여 참 값만 출력

# 위에서 한 모든것을 한 문장으로 할 수 있습니다:
print(a[a > 2])     # 출력 "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## (참조) 정수 배열 인덱싱

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print(a)

In [ ]:
# 정수 배열 인덱싱의 예.
# 반환되는 배열의 shape는 (3,)
print(a[[0, 1, 2], [0, 1, 0]])  # 출력 "[1 4 5]": ((0,0),(1,1),(2,0) 출력)

# 위에서 본 정수 배열 인덱싱 예제는 다음과 동일합니다:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # 출력 "[1 4 5]"

# 정수 배열 인덱싱을 사용할 때,
# 원본 배열의 같은 요소를 재사용할 수 있습니다:
print(a[[0, 0], [1, 1]])  # 출력 "[2 2]"

# 위 예제는 다음과 동일합니다
print(np.array([a[0, 1], a[0, 1]]))  # 출력 "[2 2]"

## 전치(transpose)

종종 배열의 모양을 바꾸거나 데이터를 처리해야 할 때가 있습니다. 가장 간단한 예는 행렬의 주 대각선을 기준으로 대칭되는 요소끼리 뒤바꾸는 것입니다;

이를 전치라고 하며 행렬을 전치하기 위해선, 간단하게 배열 객체의 ‘T’ 속성을 사용하면 됩니다:

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # 출력 "[[1 2]
            #       [3 4]]"
print(x.T)  # 출력 "[[1 3]
            #       [2 4]]"

# 차원이 1인 배열을 전치할 경우 아무 일도 일어나지 않습니다:
v = np.array([1,2,3])
print(v)    # 출력 "[1 2 3]"
print(v.T)  # 출력 "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Shape 변경

### numpy.reshape

Gives a new shape to an array without changing its data

방법1) np.arrange(6).reshape(3,2)

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a = np.arange(6).reshape((3, 2))

방법2) a를 지정한 후, np.reshape(a, (2,3))

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 2차원
np.reshape(a, (1,6))

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
# 1차원
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

### numpy.ravel()

Return a contiguous flattened array.
- neural network 학습할 때 사용 (2,3차원 데이터를 1차원으로 변경할 때)

In [ ]:
np.ravel(a) # numpy의 모듈함수인 ravel 함수 사용

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.ravel() #a의 다차원 배열의 기본 내장 함수

array([0, 1, 2, 3, 4, 5])

### numpy.ndarray.flatten()

Return a copy of the array collapsed into one dimension.

In [ ]:
# np.flatten(a) # Numpy 모듈 함수가 아님 (사용 불가)
a.flatten()     # ndarray 객체의 메소드로만 사용 가능

array([0, 1, 2, 3, 4, 5])

**ravel()과 flatten() 차이점**
- flatten은 객체의 매소드로만 사용 가능
- ravel()은 뷰(참조)를 반환, flatten은 복사본을 반환

## 연결

### numpy.concatenate
- shape가 같아야 붙음
- axis=0 : 열방향으로 붙음
- axis=1 : 행방향으로 붙음

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
np.concatenate((a, b), axis=0) #위에서 아래로 행방향으로 접합

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0:1].T

array([[1],
       [2]])

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 참조

https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html#joining-arrays

# **6.다차원 배열 연산**

기본적인 수학함수는 배열의 각 요소별로 동작하며 연산자를 통해 동작하거나 numpy 함수모듈을 통해 동작합니다.

다차원 배열간 연산시, **shape가 맞아야** 연산이 이루어집니다.
- **요소별 합, 차, 곱, 나눗셈의 경우** : shape가 일치해야 합니다.
- **dot의 경우** : 앞 배열의 열과 뒤 배열의 행의 크기가 일치해야 합니다.

https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [ ]:
import numpy as np

x = np.array([[1., 2.], [3., 4.]])
y = np.array([[5., 6.], [7., 8.]])

# 요소별 합; 둘 다 다음의 배열을 만듭니다
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# 요소별 차; 둘 다 다음의 배열을 만듭니다
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# 요소별 곱; 둘 다 다음의 배열을 만듭니다
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# 요소별 나눗셈; 둘 다 다음의 배열을 만듭니다
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# 요소별 제곱근; 다음의 배열을 만듭니다
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Numpy에선 벡터의 내적, 벡터와 행렬의 곱, 행렬곱을 위해 `*`대신 `dot`함수를 사용합니다.

`dot`은 Numpy 모듈 함수로서도 배열 객체의 메소드로서도 이용 가능한 합수입니다

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# 벡터의 내적; 둘 다 결과는 219
print(v.dot(w))   #numpy array 객체의 매개함수
print(np.dot(v, w))  #numpy 모듈 함수

# 행렬과 벡터의 곱; 둘 다 결과는 dimension 1인 배열 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# 행렬곱; 둘 다 결과는 dimension 2인 배열
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

# **7.NumPy 고급 기능**

브로트캐스팅은 Numpy에서 shape가 다른 배열 간에도 산술 연산이 가능하게 하는 메커니즘입니다. 종종 작은 배열과 큰 배열이 있을 때, 큰 배열을 대상으로 작은 배열을 여러 번 연산하고자 할 때가 있습니다. 예를 들어, 행렬의 각 행에 상수 벡터를 더하는 걸 생각해보세요. 이는 다음과 같은 방식으로 처리될 수 있습니다:

In [ ]:
import numpy as np

# 행렬 x의 각 행에 벡터 v를 더한 뒤,
# 그 결과를 행렬 y에 저장하고자 합니다
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])  #4차원 배열
# x =   "[[1  2  3]
#         [4  5  6]
#         [7  8  9]
#         [10 11 12]]"

v = np.array([1, 0, 1])   #1차원 배열


In [ ]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
v

array([1, 0, 1])

In [ ]:
x.shape

(4, 3)

In [ ]:
v.shape

(3,)

In [ ]:
y = np.empty_like(x)   # x와 동일한 shape를 가지며 비어있는 행렬 생성

y

array([[99071092587184,              0,              0],
       [             0,              0,              0],
       [             0,              0,              0],
       [             0,              0,              0]])

In [ ]:
# 명시적 반복문을 통해 행렬 x의 각 행에 벡터 v를 더하는 방법
for i in range(4):
    y[i, :] = x[i, :] + v

# 이제 y는 다음과 같습니다
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


위의 방식대로 하면 됩니다; 그러나 `x`가 매우 큰 행렬이라면, 파이썬의 반복문을 이용한 위 코드는 매우 느려질 수 있습니다.

벡터 `v`를 행렬 `x`의 각 행에 더하는 것은 `v`를 여러 개 복사해 수직으로 쌓은 행렬 `vv`를 만들고 이 `vv`를 `x`에 더하는것과 동일합니다.

이 과정을 아래처럼 구현할 수 있습니다:

In [ ]:
import numpy as np

# 벡터 v를 행렬 x의 각 행에 더한 뒤,
# 그 결과를 행렬 y에 저장하고자 합니다
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])


In [ ]:
vv = np.tile(v, (4, 1))   # tile 함수 : v의 복사본 4개를 위로 차곡차곡 쌓은 것이 vv

vv.shape

(4, 3)

In [ ]:
print(vv)                 # 출력 "[[1 0 1]
                          #       [1 0 1]
                          #       [1 0 1]
                          #       [1 0 1]]"
y = x + vv  # x와 vv의 요소별 합
print(y)    # 출력 "[[ 2  2  4
            #       [ 5  5  7]
            #       [ 8  8 10]
            #       [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy 브로드캐스팅을 이용한다면 이렇게 v의 복사본을 여러 개 만들지 않아도 동일한 연산을 할 수 있습니다. 아래는 브로드캐스팅을 이용한 예시 코드입니다:

In [ ]:
import numpy as np

# 벡터 v를 행렬 x의 각 행에 더한 뒤,
# 그 결과를 행렬 y에 저장하고자 합니다
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # numpy가 스스로 브로드캐스팅을 이용하여 v를 x의 각 행에 더하기 (shape를 변경해줘서 더함)
print(y)  # 출력 "[[ 2  2  4]
          #       [ 5  5  7]
          #       [ 8  8 10]
          #       [11 11 13]]"

(강의 처음에 나온, 수학점수 다차원 배열에 +1 한 코드도 사실은 브로드캐스팅이었습니다!)

In [ ]:
x+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
np.ones(x.shape) #1은 스칼라인데 x.shape로 브로드캐스팅하여 numpy가 더해줌.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

x의 shape가 (4, 3)이고 v의 shape가 (3,)라도 브로드캐스팅으로 인해 y = x + v는 문제없이 수행됩니다.

이때 `v`는 `v`의 복사본이 차곡차곡 쌓인 shape (4, 3)처럼 간주되어 `x`와 동일한 shape가 되며 이들 간의 요소별 덧셈연산이 y에 저장됩니다.

두 배열의 브로드캐스팅은 아래의 규칙을 따릅니다:

1. 두 배열이 동일한 dimension을 가지고 있지 않다면, 낮은 dimension의 1차원 배열이 높은 dimension 배열의 shape로 간주합니다.
2. 특정 차원에서 두 배열이 동일한 크기를 갖거나, 두 배열 중 하나의 크기가 1이라면 그 두 배열은 특정 차원에서 compatible하다고 여겨집니다.
3. 두 행렬이 모든 차원에서 compatible하다면, 브로드캐스팅이 가능합니다.
4. 브로드캐스팅이 이뤄지면, 각 배열 shape의 요소별 최소공배수로 이루어진 shape가 두 배열의 shape로 간주합니다.
5. 차원에 상관없이 크기가 1인 배열과 1보다 큰 배열이 있을 때, 크기가 1인 배열은 자신의 차원 수만큼 복사되어 쌓인 것처럼 간주합니다.

브로드캐스팅을 지원하는 함수를 universal functions라고 합니다.

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

브로드캐스팅을 응용한 예시들입니다:

In [ ]:
import numpy as np

v = np.array([1,2,3])  # v의 shape는 (3,)
w = np.array([4,5])    # w의 shape는 (2,)
x = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 벡터를 행렬의 각 행에 더하기
# x는 shape가 (2, 3)이고 v는 shape가 (3,)이므로 이 둘을 브로드캐스팅하면 shape가 (2, 3)인
# 아래와 같은 행렬이 나옵니다:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 4 6]
 [5 7 9]]


Transpose를 이용해서 배열 맞지 않은 w와 x 더하기

In [ ]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
w

array([4, 5])

In [ ]:
x.T + w

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [ ]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
# 벡터를 행렬의 각 행에 더하기
# x는 shape가 (2, 3)이고 w는 shape가 (2,)입니다.
# x의 전치행렬은 shape가 (3,2)이며 이는 w와 브로드캐스팅이 가능하고 결과로 shape가 (3,2)인 행렬이 생깁니다;
# 이 행렬을 전치하면 shape가 (2,3)인 행렬이 나오며
# 이는 행렬 x의 각 열에 벡터 w을 더한 결과와 동일합니다.
# 아래의 행렬입니다:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


reshape 이용해서 w와 x 더하기

In [ ]:
w  #1차원

array([4, 5])

In [ ]:
 np.reshape(w, (2, 1))  #열 벡터로 변환

array([[4],
       [5]])

In [ ]:
# 다른 방법은 w를 shape가 (2,1)인 열벡터로 변환하는 것입니다;
# 그런 다음 이를 바로 x에 브로드캐스팅해 더하면
# 동일한 결과가 나옵니다.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# 행렬의 스칼라배:
# x 의 shape는 (2, 3)입니다. Numpy는 스칼라를 shape가 ()인 배열로 취급합니다;
# 그렇기에 스칼라 값은 (2,3) shape로 브로드캐스트 될 수 있고,
# 아래와 같은 결과를 만들어 냅니다:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


브로드캐스팅은 보통 코드를 간결하고 빠르게 해줍니다, 그러니 가능한 많이 사용하세요.